image: Visual Studio 2017
version: 2.0.{build}
configuration: Release
before_build:
- nuget restore
build:
  project: ZendeskApiClient.sln
  parallel: true
  verbosity: minimal
test:
  assemblies:
    except:
      - test-assembly-A.dll
      - '**\*.Acceptance.dll'
artifacts:
- path: 'output\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 6MzbzEs4YdJKS67Gio5gEO8mNKmwfC4UHTCmECZ1KOutI6ndm4vAECazmVNB6an7
  artifact: /.*nupkg/
  on:
    APPVEYOR_REPO_TAG: true
